heat_template_version: 2021-04-16
description: >
  Create instance and add it to the Load Balancer pool if the
  "lb_pool" parameter is specified.
parameters:
  image:
    type: string
    description: The ID or name of the image to boot with
  flavor:
    type: string
    description: The ID or name of the flavor to boot onto
  key_name:
    type: string
    description: Name of keypair to inject into the server
  subnet:
    type: string
    description: Subnet name or ID of this member
  security_groups:
    type: comma_delimited_list
    description: List of security group names or IDs
  user_data:
    type: string
    description: Instance user data
  metadata:
    type: json
    description: Instance metadata
  lb_pool:
    type: string
    description: Name or ID of the load balancing pool
    default: ""
  lb_member_port:
    type: number
    description: Port on which the pool member listens for requests or connections
    default: 80

conditions:
  add_to_pool:
    not:
      equals:
        - get_param: lb_pool
        - ""

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      user_data: {get_param: user_data}
      user_data_format: RAW
      security_groups: {get_param: security_groups}
      networks: [{subnet: {get_param: subnet} }]
  member:
    type: OS::Octavia::PoolMember
    properties:
      pool: {get_param: lb_pool}
      address: {get_attr: [server, first_address]}
      protocol_port: {get_param: lb_member_port}
      subnet: {get_param: subnet}
    condition: add_to_pool

outputs:
  server_ip:
    description: Instance IP address
    value: {get_attr: [server, first_address]}
  server_name:
    description: Instance name
    value: {get_attr: [server, name]}
  lb_member:
    description: Load balancer member details
    value: {get_attr: [member, show]}
    condition: add_to_pool
